### PR TITLE
Writing Experiments - Styling Ticket 2

### PR DESCRIPTION
**Pull request by chelyfern**

### CODE REVIEW

**Comment by floan** [comment]
@ChelyFernandezUSC just pushed some [styling changes](https://github.com/ctcusc/WriteGirl-BoldInkWriters/pull/5/commits/91e4e9f65f4bd6efc0efdf2a5ea07031a28608bf). Here's how the button looks after it (Iphone SE and Ipad Air). Happy to answer any questions you might have! 

Screen Shot 2023-01-22 at 3 49 28 PM
Screen Shot 2023-01-22 at 3 49 45 PM

**Comment by chelyfern** [comment]
@floan that looks so good!! Now I see how the position: 'absolute' should be used in only specific cases. Also, what does paddingVertical/paddingHorizontal for smallButtons do? Thank you for your help!!!

**Comment by floan** [comment]
@ChelyFernandezUSC `paddingVertical` acts as `paddingTop` and `paddingBottom` and `paddingHorizontal` acts as `paddingLeft` and `paddingRight`, so using them in `smallButtons` helps me add some padding around the text, otherwise the button's `height`/`width` would be as large as the text. 

I now realize the div I called `buttonPadding` should probably be `buttonMargin` (you can change that!). Basically because we have positioned the button itself as absolute, it can overlap the text if the box is not big enough, or we don't move the text around. (Hypothetical scenario: if the box is 10 pixels, and text is in the middle (lets say it spans pixel number 5 and 6 out of 10), and the button is 5 pixels and at the bottom of the box, pixel 1 of the button will overlap with the last pixel of the text). If this example doesn't make sense to you let me know and I'll show you how it looks in person! 

But so basically, by adding `buttonPadding` I'm adding a new `relative` div the same size of the button. This div is invisible (no bg color & nothing inside it), but it acts as a relative button which will push the text up. (Remember on Thursday when we centered the button, it automatically took care of not overlapping with the text?). This way the "invisible button" will always prevent the text from overlapping with the actual button. The only reason why we didn't use this div as the actual button class is because its very hard to always accurately position a `relative` div on the bottom right. Now this acts as `margin` because it is pushing the text away from the button. (Padding is space inside the component, margin is space outside the component). Also we couldn't just use `margin` or `marginTop` or something similar because none of them work when you use `position: absolute`.

Hope that makes sense! Let me know if you have any other questions. (Also I'm not sure if this is the only / the best way to do this, but it works 😅)

**Comment by chelyfern** [comment]
@floan Okay that makes sense! I think it would be helpful to go over that example in person today though just to make sure I understand, and to talk about the "invisible button" a bit more Lol. Thank you again!!

**Comment by ipekgoktan** [comment]
Tried it out on my end and it looks great! Awesome job with styling and scaling!!

My only feedback is please try to use a separate page for styling in your future sprints using the following format:
    - A folder called <YourPageName> (which you had, good job!)
        - <YourPageName>.js
            - this file is inside your folder, this is where you write the code that makes up your page
        - <YourPageName>Style.js
            - this file inside your folder, styling sheet for your page

**Comment by floan** [comment]
@ChelyFernandezUSC sorry just seeing this!!! Can discuss on Thursday if you want more clarification!

**Review by ipekgoktan — APPROVED** [review]
Great job!

**Pull request merged**
